version: '2'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    links:
    - redis
  redis:
    image: redis
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb: