service: collaborationEngine

custom:
  output:
    file: ./data.json
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  stage: lab
  region: us-east-2
  profile: liquid

  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB

  runtime: nodejs14.x
  timeout: 30

  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    APIG_ENDPOINT:
      Fn::Join:
        - ""
        - - Ref: WebsocketsApi
          - .execute-api.
          - Ref: AWS::Region
          - .amazonaws.com/
          - ${self:provider.stage}
    CONNECTIONS_TABLE:
      Ref: YConnectionsTable

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:DeleteItem
            - dynamodb:GetItem
            - dynamodb:Scan
            - dynamodb:PutItem
          Resource:
            - "arn:aws:dynamodb:::table/YConnectionsTable"

functions:
  api:
    handler: main.handler
    events:
      - websocket:
          # Handles new connection requests
          route: $connect
          # Only the '$connect' route supports an authorizer. The other routes
          # are secured via the connection ID and therefore it should be handled
          # like a session ID.

      - websocket:
          # Route messages here if '$request.body.action' is 'routeA'.
          # You can adjust which property to use for routing by adjusting
          # 'websocketsApiRouteSelectionExpression'.
          route: routeA
      - websocket:
          # Handles all unrouted messages
          route: $default
      - websocket:
          # Handles disconnect messages
          route: $disconnect

resources:
  Resources:
    YConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: YConnectionsTable
        AttributeDefinitions:
          - AttributeName: PartitionKey
            AttributeType: S
          - AttributeName: DocName
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: DocNameIndex
            KeySchema:
              - AttributeName: DocName
                KeyType: HASH
            Projection:
              NonKeyAttributes:
                - Updates
              ProjectionType: INCLUDE
        KeySchema:
          - AttributeName: PartitionKey
            KeyType: HASH
        SSESpecification:
          SSEEnabled: true
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
